# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-iTunes-Library
version:      0.62
version_from: lib/Mac/iTunes/Library.pm
installdirs:  site
requires:
    XML::Parser:                 2.36

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
